version: '1.0'

services:
  culina-db:
    container_name: culina-db
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=qwaq
      - POSTGRES_PASSWORD=qwaq
      - POSTGRES_DB=Culina-app
    ports: 
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: