env: "dev"
server:
  port: ":8080"
database:
  host: "localhost"
  port: "5432"
  db_name: "Culina-app-go"
  db_password: "qwaq"
  db_username: "qwaq"
  sslmode: "disable"
typesense:
  host: "http://localhost:8108"
  api_key: "zxc"